name: Run End-to-End Tests

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    env:
      CI: true
      PUPPETEER_SKIP_DOWNLOAD: false
      TEST_ENV: true
      GET_CONTENT_ENDPOINT: "http://localhost:8080"
      PROJECT_ID: "qeen-web-staging"
      BQ_DATASET: "staging_qeen_web_analytics"
      BQ_EVENTS_TABLE: "events"
      BQ_EVENTS_TABLE_NPDP: "non_pdp_events"
      ANALYTICS_HOST: "https://web-analytics-342357195876.europe-west1.run.app"
      GCP_WORKLOAD_ID_PROVIDER: ${{ secrets.STG_GCP_WORKLOAD_ID_PROVIDER }}

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Print secrets for testing
        run: |
          echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
          echo "GCP_WORKLOAD_ID_PROVIDER: ${{ env.GCP_WORKLOAD_ID_PROVIDER }}"

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.GCP_WORKLOAD_ID_PROVIDER }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run build

      - name: Build playground
        run: |
          cd test
          cat .env
          echo "REACT_APP_ANALYTICS_HOST=$ANALYTICS_HOST" >> .env
          npm install
          npm run build
          cd ..

      - name: Run tests
        run: npm run test:e2e
